### ISSUE TITLE
Assigning and adjusting the zoom ratio does not seem to work

### ISSUE THREAD

**Issue by marcelosud** [jackmoore/wheelzoom#30]
Hello, I need help.
I tried using the zoom percentage adjustment feature and it is not getting the new value received.

I followed the example:
_Wheelzoom (document.querySelectorAll ('img'), {zoom: 0.05});_

I changed the value of 'zoom: 0.05' to other values like '0.05', '0.50', '10.00' and others ... did not make any difference.

**I tested by adding a new default variable to test with an 'Alert' inside the script and also did not change the value:**

_Wheelzoom (document.querySelectorAll ('img'), {direction: 5});_

**And added the default variable:**

_Window.wheelzoom = (function () {
Var defaults = {
Zoom: 0.10,
MaxZoom: false,
**_Direction: 1_**
};_

**Alert only shows '1' and not 5 assigned.**

What could be the problem? Or what can I be doing wrong?
From now on, thank you very much for your contribution with this script, really very useful and has helped me a lot until now.

**Comment by jackmoore** [comment]
The fact that your direction value wasn't updated is fine and expected.  The script isn't merging the whole defaults object into a new settings object, it's just looking at the values it actually uses (zoom and maxZoom).

I don't know why changing the zoom value didn't work.  Since that's not something I can reproduce, it would help if you provided a link that demonstrates the problem.
